### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by qassisju** [qassisju/MI-449-SS17-741-js-objects-T4W3KQ#1]
@egillespie Can you take a look at this? It's [hosted here](https://qassisju-kaprwtcydf6wbt4w3kq.surge.sh/) and meets the following criteria:

- [x] Your app builds on [these files](https://gist.github.com/chrisvfritz/3bd1b8d8e5b0d1ea2278ffbc561de047) (you can make changes to any of them)
- [x] When the `requestedJokeInput` has a value matching the key of an existing joke, the `jokeBox` HTML is updated [in this format](https://gist.github.com/chrisvfritz/4def3c246dfb931ecb57384a5639af99)
- [x] When the `requestedJokeInput` does _not_ match an existing joke, the `jokeBox` content is updated to `No matching joke found.`
- [x] When the `Remember this joke!` button is clicked, a new joke is saved (or overwritten) in the `jokes` object, using the data in the associated `input`/`textarea` elements
- [x] When the `Forget about it!` button is clicked, the joke with that key (if any) is deleted from the `jokes` object
- [x] Whenever the `jokes` object changes, the new version is saved in `localStorage` and used whenever the user visits the page again
- [x] It's impossible for an error to ever occur in the JavaScript console

**Comment by egillespie** [comment]
I really like how you've organized your code and for the most part, the page is functioning really well! 😂

I do see a couple of quirks that I'd like you to fix though:

### Linting HTML

The changes you made to the HTML do not have valid syntax. Please go back to [lesson 3](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-boilerplate-linting-and-code-style/2) and follow the instructions to install the HTML linter to Atom and correct these.

### Saved jokes not displayed when I refresh

Everything appears to be working correctly on the page, but I noticed that after I add a joke and refresh the page, `localStorage` is not being used. Instead, I get the two default jokes again.

Can you update your page to use the jokes in `localStorage` if they exist?

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by qassisju** [comment]
these two should be fixed now!

**Comment by egillespie** [comment]
The HTML looks good. The saved jokes still aren't displaying when I refresh the page, though.

It looks like you're missing the parentheses when you call `loadJokes`:

https://github.com/qassisju/MI-449-SS17-741-js-objects-T4W3KQ/blob/master/app.js#L70

Add the parentheses and test your changes. Once it's working, comment here and I'll check it out again.

Thanks! 🎸

**Comment by qassisju** [comment]
I added parenthesis to that function call

**Comment by egillespie** [comment]
Hmm, it looks like it's still not working. On [line 98](https://github.com/qassisju/MI-449-SS17-741-js-objects-T4W3KQ/blob/master/app.js#L98) it looks like you need to assign the parsed JSON to `jokes`.

Try that out and verify your changes on Surge, then comment back here and I'll give it another look.

Thanks! 🌵

**Comment by qassisju** [comment]
Okay I tested it and it seems to be working now!

**Comment by egillespie** [comment]
Works great now, good work! :shipit:
